project_id = "fgpnrblralcjbceznnef"

[functions.process-csv]
verify_jwt = false

[functions.run-billing]
verify_jwt = false

[functions.generate-invoices]
verify_jwt = false

[functions.create-organization]
verify_jwt = false
